test_square (__main__.TestExercice) ... FAIL
test_square_root (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_square (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 23, in test_square
    'Failed to calculate squares'
AssertionError: Lists differ: [None, None, None, None, None, None, None,[553 chars]None] != [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, [507 chars]9801]

First differing element 0:
None
0

Diff is 1754 characters long. Set self.maxDiff to None to see it. : Failed to calculate squares

======================================================================
FAIL: test_square_root (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 33, in test_square_root
    'Failed to calculate square roots'
AssertionError: Lists differ: [None, None, None, None, None, None, None,[553 chars]None] != [0.0, 1.0, 1.4142135623730951, 1.732050807[1699 chars]0662]

First differing element 0:
None
0.0

Diff is 2946 characters long. Set self.maxDiff to None to see it. : Failed to calculate square roots

----------------------------------------------------------------------
Ran 2 tests in 0.044s

FAILED (failures=2)
